import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Analytics } from "@vercel/analytics/react";
import "./globals.css";
import { Layout } from "@/components/ds";
import { Navigation } from "@/components/custom-components/navigation";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <Layout>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <Navigation items={[
                    { href: "#vores-mission", label: "Vores mission" },
                    { href: "#vores-indsats", label: "Vores indsats" },
                    { href: "#kontakt-os", label: "Kontakt os" },
                ]} />
                {children}
                <Analytics />
            </body>
        </Layout>
    );
}
